"""Len

Revision ID: 223333a51d9d
Revises: 6454e623864d
Create Date: 2024-07-06 09:25:16.279747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223333a51d9d'
down_revision = '6454e623864d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=320),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=2),
               existing_nullable=True)
        batch_op.create_unique_constraint('uix_user_email', ['email'])
        batch_op.create_unique_constraint('uix_user_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uix_user_username', type_='unique')
        batch_op.drop_constraint('uix_user_email', type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=320),
               existing_nullable=False)

    # ### end Alembic commands ###
