"""Added interests

Revision ID: b6fb6fd2bfdf
Revises: 0d6cb5e92ac2
Create Date: 2024-07-07 15:46:19.772291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6fb6fd2bfdf'
down_revision = '0d6cb5e92ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interests', sa.Enum('travel', 'football', 'walking', 'gym', 'movies', 'music', 'tatoos', 'coffee', 'netflix', 'shopping', 'outdoors', 'nightlife', 'food', 'sports', 'universities', 'nerd', 'beer', 'work', 'dogs', 'cats', name='interests_enum'), nullable=True))
        batch_op.drop_column('interest')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('interests')

    # ### end Alembic commands ###
