"""Added Gender Options

Revision ID: c97dcf107201
Revises: 223333a51d9d
Create Date: 2024-07-06 23:46:50.817128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c97dcf107201'
down_revision = '223333a51d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_urls', sa.String(), nullable=True))
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('image_urls')

    # ### end Alembic commands ###
